---
- name: Install Nginx Repository
  copy: src=config dest=/etc/yum.repos.d/nginx.repo owner=root group=root

- name: Enable nginx Repository
  command: yum-config-manager --enable nginx-stable

- name: Install Nginx
  yum: name=nginx state=latest

- name: Automatic load when boot
  command: systemctl enable nginx.service

- name: Create Folder for fefault source
  file: path={{web_root}} state=directory owner=nginx group=nobody mode=755

- name: Copy index file for default folder
  template: src=index.php.j2 dest={{web_root}}/index.php owner=nginx group=nobody mode=655

- name: Copy Nginx Main configuration
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf mode=0644

- name: Copy Nginx Options configuration
  template: src=options.conf.j2 dest=/etc/nginx/options.conf mode=0644

- name: Copy www default configuration
  template: src=default.conf.j2 dest=/etc/nginx/conf.d/default.conf owner=nginx group=nobody mode=0644
  vars:
    web_root_a: "{{web_root}}"

- name: Be sure nginx is running and enable
  service: name=nginx state=started enabled=true

- name: Be sure firewalld is running and enable
  service: name=firewalld state=started enabled=true

- name: Change filter on firewalld.service http
  command: firewall-cmd --permanent --zone=public --add-service=http

- name: Change filter on firewalld.service https
  command: firewall-cmd --permanent --zone=public --add-service=https

- name: Restart firewalld
  command: systemctl restart firewalld.service