---
- name: Init Repo
  template: src=mongodb.repo.j2 dest=/etc/yum.repos.d/mongodb.repo

- name: Install mongodb
  command: yum -y install mongodb-org

- name: Start mongodb
  command: systemctl enable mongod
  command: systemctl start mongod

- name: Install php-mongo
  command: pecl install mongo