---
- name: Install postgresql Database
  yum: name={{ item }} state=present
  with_items:
  - postgresql-server
  - postgresql-contrib

- name: Create new cluster
  command: postgresql-setup initdb

- name: Load configuration file
  template: src=pg_hba.conf.j2 dest=/var/lib/pgsql/data/pg_hba.conf

- name: Automatic load when boot
  command: systemctl enable postgresql.service

- name: Be sure postgresql is running and enable
  service: name=postgresql state=running enabled=true