---
- name: be sure firewalld is running and enabled
  service: name=firewalld state=started enabled=true

- name: enable http(80) to public
  command: firewall-cmd --permanent --zone=public --add-service=http
  notify: 
  - restart firewalld.service

- name: enabled https(443) to public
  command: firewall-cmd --permanent --zone=public --add-service=http
  notify: 
  - restart firewalld.service

# - name: enable 8080/tcp port to public or custom port to ssh
  # command: firewall-cmd --permanent --zone=public --add-port=8080/tcp
  # notify: 
  # - restart firewalld.service