---
- name: Install Epel repository
  command: rpm -Uivh --replacepkgs {{epel_repository}}

- name: Install Remi repository
  command: rpm -Uivh --replacepkgs {{remi_repository}}

- name: Change SELinux Policy Mode
  command: setenforce 0
  ignore_errors: True

- name: Copy SELinux configuration file
  copy: src=config dest=/etc/selinux/config owner=root group=root

- name: Install wget
  yum: name=wget state=present

- name: Install gcc
  yum: name=gcc state=present

- name: Install Git
  yum: name=git state=present

- name: Install VIM
  yum: name=vim state=present

- name: Install Net tools
  yum: name=net-tools state=present