---
- name: Install requirement packages
  yum: name={{ item }} state=latest
  with_items:
   - php-devel
   - pcre-devel
   - gcc
   - make

- name: Make sure cphalcon is absent
  file: path=/home/vagrant/cphalcon state=absent

- name: Clone Phalcon Repository
  command: git clone --depth=1 {{phalcon_repository}}

- name: Install Phalcon
  command: sudo ./install chdir=/home/vagrant/cphalcon/build

- name: Enable phalcon
  copy: src=phalcon.ini dest=/etc/php.d/phalcon.ini owner=root group=root mode=770

- name: Restart php-fpm.service
  command: systemctl restart php-fpm.service